name: Docker Security Scan

on:
  push:
    branches: [main]

jobs:
  docker-audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Scan Docker image
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: your-docker-image:latest